### ISSUE TITLE
What have you moved to?

### ISSUE THREAD

**Issue by freekeys** [marvin-hansen/IB-gateway#1]
Hello! I'm interested to know what you're now using instead? How are you finding it? Thanks!

**Comment by marvin-hansen** [comment]
@freekeys 

Essentially, I moved to crypto. After a lot of trial & error, I ended up using Trdadingview to accelerate my strategy development, wunderbit to run my strategies, and FTX as crypto exchange.

1) Tradingview (TV) uses Pinescript, gives you free data for almost anything crypto, and comes with an okay backtester. Developing & testing a trading stratetegy is considerably faster than anything i have used before. TV gives you a generous 30 day free premium trial, which gives you plenty of time to produce a handful of good trading strategies. 

You get an additional $30 discount when using this link:
https://www.tradingview.com/gopro/?share_your_love=MarvinHansen

2) Wunderbit -  I mean, I have tried & tested virtually all automated crypto trading sites on the internet, and most  of them  are junk, one way or the other. Wunderbit on the other hand gives me exactly what I want, that is:

- Seemless Tradingview integration. 
- Supports many exchanges 
- Does not impose a stupid framework or "everything DCA" design
- Allows you to earn additionalk money when renting your algo for a monthly fee 
- Allows you to get paid when other copy your trades through the build in copy trade system 

This is very useful and works exactly as they say. 

You get a 10% discount when using the link below. 

https://trading.wunderbit.co/en/trader/register?ref=wbt99774db4 

Notice, wunderbit does NOT supports paper trading. Only live. For paper trading you can use something like 3commas although it's very basic and more of a toy, at best.  


3) FTX

When you compare trading commissions you soon figure out that not only Binace is the second most expensive exchange on the market but also suffers frequent flash crashes or hour long take outs. I think Binance US had its last flash crash just a few weeks ago, and when BTC was going down in May, Binance simply stopped trading for several hours resulting in many people facing substantial or complete loss of all their money. 

FTX on the other hand 
- Is build by some smart cookies from MIT who worked in institutional investment before 
- has among the lowest fee in the industry by default
- Gives you sub-accounts with dedicated API keys per sub-account so you can clearly separate various algo's and limited risk to only the sub-account. This comes in handy. 
- Gives you Discount when staking their coin. (That is way easier to do than reaching bulk volume discount)  
- Just runs, no flash crashes and no take outs. 

However, not many auto-trading sites support FTX yet despite its phenomenal growth and excellent platform. 
Wunderbit, actually  does although they currently only support spot & leverage tokens. Futures will come later.   

When you use the link below, you get an 5% discount on all trading fees on FTX: 

https://ftx.com/profile#a=GHDISCOUNT 

With that said, my workflow is pretty streamlined: 

1) Develop & backtest strategy in trading view
- Develop on one coin, say ETH
- Test it one various others coins to see if it generalizes. It should work on at least 2 -3 other major coins to be conisiderd
- Make a copy for each coin  that looks promising and optimize parameters to find best match

This may take a day or two, depending on how robust the core strategy is 

2) May or may not run paper trading. Again, it depends on how robust the strategy is  

3) Integrate into Wunderbit, which takes maybe 3 to 5 minutes depending on how fast you can copy & paste the order messages into your Tradingview code. 

And let it run. 

The setup takes at most a few hours on the weekend, and then eveyrthing is fast & streamlined. On a normal day, I spent about 60 % of my work time coding strategies and the other 40% researching new strategies. Because it's crypto, creativity actually wins so you really have to run through a lot of try & error before you find something that works well. 


Hope that helps.

**Comment by freekeys** [comment]
Thanks so much for your answer!
